export const AI_CATEGORIES = [
  { id: "writing", name: "Writing & Content", icon: "✍️", color: "#9D4EDD" },
  { id: "image", name: "Image & Design", icon: "🎨", color: "#7209B7" },
  { id: "video", name: "Video & Audio", icon: "🎬", color: "#560BAD" },
  { id: "coding", name: "Coding & Development", icon: "💻", color: "#3A0CA3" },
  { id: "productivity", name: "Productivity & Automation", icon: "⚡", color: "#4361EE" },
  { id: "reasoning", name: "Reasoning & Analysis", icon: "🧠", color: "#4895EF" },
  { id: "marketing", name: "Marketing & Sales", icon: "📊", color: "#06FFA5" },
  { id: "search", name: "Search & Discovery", icon: "🔍", color: "#FB5607" },
];

export const AI_TOOLS = [
  { id: "chatgpt", name: "ChatGPT", category: "writing", description: "Advanced conversational AI for content creation, analysis, and problem-solving", pricing: "Free / $20/mo", rating: 4.9, reviews: 5432, features: ["Content generation", "Code assistance", "Analysis"], url: "https://chat.openai.com", isFeatured: true },
  { id: "midjourney", name: "Midjourney", category: "image", description: "Premium AI image generation with exceptional visual quality and artistic styles", pricing: "$10-30/mo", rating: 4.9, reviews: 3210, features: ["High-quality images", "Artistic styles", "Upscaling"], url: "https://midjourney.com", isFeatured: true },
  { id: "claude", name: "Claude (Coding)", category: "coding", description: "Claude AI specialized for code analysis and generation with superior reasoning", pricing: "Free / $20/mo", rating: 4.9, reviews: 2987, features: ["Code analysis", "Debugging", "Code generation"], url: "https://claude.ai", isFeatured: true },
  { id: "claude-reasoning", name: "Claude Reasoning & Analysis", category: "reasoning", description: "Anthropic's advanced reasoning capabilities for complex problem solving", pricing: "Free / $20/mo", rating: 4.8, reviews: 1876, features: ["Long context", "Code analysis", "Analysis"], url: "https://claude.ai", isFeatured: false },
  { id: "figma-ai", name: "Figma with AI", category: "image", description: "Design tool enhanced with AI features for rapid prototyping", pricing: "$12-240/mo", rating: 4.8, reviews: 2234, features: ["AI input", "Component variants", "Design systems"], url: "https://figma.com", isFeatured: false },
  { id: "synthesia", name: "Synthesia", category: "video", description: "Enterprise AI video generation with 250+ avatars and 80+ languages", pricing: "$25-480/mo", rating: 4.8, reviews: 1765, features: ["Multiple avatars", "Multilingual", "Enterprise"], url: "https://synthesia.io", isFeatured: false },
  { id: "elevenlabs", name: "ElevenLabs", category: "video", description: "Most realistic AI voice generation with 300+ voices and natural speech", pricing: "Free / $5-99/mo", rating: 4.4, reviews: 2156, features: ["Voice cloning", "300+ voices", "Natural speech"], url: "https://elevenlabs.io", isFeatured: false },
  { id: "github-copilot", name: "GitHub Copilot", category: "coding", description: "AI code assistant powered by Codex for faster development", pricing: "$10/mo", rating: 4.8, reviews: 3456, features: ["Code completion", "Multiple languages", "Code analysis"], url: "https://github.com/features/copilot", isFeatured: false },
  { id: "zapier", name: "Zapier", category: "productivity", description: "AI-powered automation connecting 7000+ apps with natural language", pricing: "Free / $19-99/mo", rating: 4.8, reviews: 2543, features: ["7000+ integrations", "AI automation", "Workflows"], url: "https://zapier.com", isFeatured: false },
  { id: "gemini", name: "Google Gemini", category: "reasoning", description: "Google's multimodal AI with advanced reasoning and image understanding", pricing: "Free / $20/mo", rating: 4.7, reviews: 1765, features: ["Multimodal", "Web search", "Analysis"], url: "https://gemini.google.com", isFeatured: false },
  { id: "grammarly", name: "Grammarly", category: "writing", description: "AI writing assistant for grammar, tone, and clarity improvement", pricing: "Free / $12/mo", rating: 4.7, reviews: 2876, features: ["Grammar check", "Tone detection", "Clarity"], url: "https://grammarly.com", isFeatured: false },
  { id: "dalle3", name: "DALL-E 3", category: "image", description: "OpenAI's advanced image generation with excellent prompt understanding", pricing: "Free / $15/mo", rating: 4.7, reviews: 1987, features: ["Text-to-image", "Editing", "Variations"], url: "https://openai.com/dall-e-3", isFeatured: false },
  { id: "canva", name: "Canva AI", category: "image", description: "Design platform with AI-powered features for quick creation", pricing: "Free / $13/mo", rating: 4.6, reviews: 2134, features: ["Templates", "AI design", "Collaboration"], url: "https://canva.com", isFeatured: false },
  { id: "heygen", name: "HeyGen", category: "video", description: "AI video creation with realistic avatars and lip-sync", pricing: "Free / $15-99/mo", rating: 4.7, reviews: 1654, features: ["Talking avatars", "Lip-sync", "Multi-language"], url: "https://heygen.com", isFeatured: false },
  { id: "suno", name: "Suno", category: "video", description: "AI music generation creating original songs from text descriptions", pricing: "Free / $10-32/mo", rating: 4.7, reviews: 1432, features: ["Music generation", "Lyrics creation", "Style control"], url: "https://suno.ai", isFeatured: false },
  { id: "cursor", name: "Cursor", category: "coding", description: "AI-first code editor with built-in Claude integration", pricing: "Free / $20/mo", rating: 4.7, reviews: 1123, features: ["AI editing", "Code generation", "Debugging"], url: "https://cursor.sh", isFeatured: false },
  { id: "bolt", name: "Bolt.new", category: "coding", description: "AI web development tool for building full-stack applications", pricing: "Free / $20/mo", rating: 4.7, reviews: 987, features: ["Full-stack generation", "Real-time preview", "AI assistance"], url: "https://bolt.new", isFeatured: false },
  { id: "make", name: "Make (Integromat)", category: "productivity", description: "Visual automation platform with AI-powered workflow creation", pricing: "Free / $9-299/mo", rating: 4.7, reviews: 2234, features: ["1000+ integrations", "Visual builder", "AI workflows"], url: "https://make.com", isFeatured: false },
  { id: "otterai", name: "Otter.ai", category: "productivity", description: "Real-time transcription and meeting notes with AI summarization", pricing: "Free / $10-30/mo", rating: 4.6, reviews: 1876, features: ["Live transcription", "Summaries", "Search"], url: "https://otter.ai", isFeatured: false },
  { id: "hubspot", name: "HubSpot AI", category: "marketing", description: "AI-enhanced CRM with data scoring and content generation", pricing: "Free / $50-3200/mo", rating: 4.7, reviews: 2543, features: ["Lead scoring", "Content AI", "Analytics"], url: "https://hubspot.com", isFeatured: false },
  { id: "jasper", name: "Jasper", category: "writing", description: "Marketing-focused AI content generation platform", pricing: "Free / $39-125/mo", rating: 4.8, reviews: 1654, features: ["Brand voice", "Templates", "API"], url: "https://jasper.ai", isFeatured: false },
  { id: "stablediffusion", name: "Stable Diffusion", category: "image", description: "Open-source image generation model available for local use", pricing: "Free", rating: 4.6, reviews: 1345, features: ["Open source", "Community models", "Local use"], url: "https://stablediffusionweb.com", isFeatured: false },
  { id: "runway", name: "Runway", category: "video", description: "AI video editing and generation with motion tracking", pricing: "Free / $12-76/mo", rating: 4.7, reviews: 1543, features: ["Video generation", "Motion tracking", "Editing"], url: "https://runway.com", isFeatured: false },
  { id: "windsurf", name: "Windsurf", category: "coding", description: "Advanced code editor with AI-powered flow state development", pricing: "Free / $20/mo", rating: 4.8, reviews: 1234, features: ["Flow mode", "AI assistance", "Code generation"], url: "https://windsurf.dev", isFeatured: false },
  { id: "lovable", name: "Lovable", category: "coding", description: "AI-powered web app builder for rapid development", pricing: "Free / $20/mo", rating: 4.6, reviews: 1043, features: ["App generation", "Real-time", "Deployment"], url: "https://lovable.dev", isFeatured: false },
  { id: "fireflies", name: "Fireflies.ai", category: "productivity", description: "AI meeting transcription and conversation intelligence", pricing: "Free / $10-19/mo", rating: 4.7, reviews: 1432, features: ["Meeting transcription", "Summaries", "Search"], url: "https://fireflies.ai", isFeatured: false },
  { id: "gamma", name: "Gamma", category: "writing", description: "AI presentation generator creating professional slides instantly", pricing: "Free / $8-25/mo", rating: 4.7, reviews: 1234, features: ["Slide generation", "Design", "Collaboration"], url: "https://gamma.app", isFeatured: false },
  { id: "notionai", name: "Notion AI", category: "productivity", description: "AI integration into Notion for content generation and summarization", pricing: "Free / $8-10/mo", rating: 4.6, reviews: 1876, features: ["Content generation", "Summarization", "Integration"], url: "https://notion.so", isFeatured: false },
  { id: "copyai", name: "Copy.ai", category: "marketing", description: "AI copywriting tool for marketing content and sales pages", pricing: "Free / $49-499/mo", rating: 4.9, reviews: 1543, features: ["Copywriting", "Landing pages", "Email"], url: "https://copy.ai", isFeatured: false },
  { id: "theresan", name: "There's An AI For That", category: "search", description: "Task-based AI tool search engine helping find right AI for your needs", pricing: "Free", rating: 4.5, reviews: 876, features: ["Tool search", "Task-based", "Comparison"], url: "https://www.theresanaiforthat.com", isFeatured: false },
  { id: "aitoolsdirectory", name: "AI Tools Directory", category: "search", description: "Comprehensive directory of AI tools with categorization", pricing: "Free", rating: 4.4, reviews: 654, features: ["Tool directory", "Categories", "Comparison"], url: "https://www.aitoolsdirectory.com", isFeatured: false },
  { id: "lookkle", name: "Lookkle", category: "search", description: "AI tools discovery platform with smart recommendations", pricing: "Free", rating: 4.5, reviews: 765, features: ["Discovery", "Recommendations", "Reviews"], url: "https://lookkle.com", isFeatured: false },
];

// 50+ VISIONARY AI POSSIBILITIES - COMPREHENSIVE FRONTIER COVERAGE
export const VISIONARY_POSSIBILITIES = [
  // MIND-BENDING PERCEPTION
  { id: "hallucinations", title: "AI Hallucinations & Impossible Realities", icon: "🌀", color: "#FF006E", description: "Explore the beautiful chaos of AI-generated hallucinations and impossible worlds", possibilities: ["Surreal dreamscapes that defy physics", "Impossible architecture that shouldn't exist", "Creatures from alternate dimensions", "Recursive, self-referential visual paradoxes", "Consciousness-expanding abstract visualizations"], tools: ["Midjourney", "DALL-E 3", "Stable Diffusion", "Claude", "GPT-4"] },
  { id: "optical-illusions", title: "Optical Illusions & Visual Trickery", icon: "👁️", color: "#FB5607", description: "Master the art of visual deception and perception manipulation", possibilities: ["M.C. Escher-inspired impossible geometries", "Optical illusions that trick the human brain", "Morphing shapes that challenge perception", "Impossible perspectives and viewpoints", "Visual paradoxes that loop infinitely"], tools: ["Midjourney", "Runway", "Figma AI", "Stable Diffusion", "DALL-E 3"] },
  { id: "deepfakes-reality", title: "Deepfakes & Reality Distortion", icon: "🎭", color: "#FFBE0B", description: "Blur the line between real and synthetic, truth and fiction", possibilities: ["Photorealistic deepfakes of historical moments", "AI-generated celebrity performances", "Synthetic news and alternate histories", "Reality-bending video compositions", "Undetectable AI-generated media"], tools: ["HeyGen", "Synthesia", "Runway", "D-ID", "ElevenLabs"] },
  { id: "psychedelic-ai", title: "Psychedelic AI & Consciousness Expansion", icon: "🔮", color: "#8338EC", description: "Generate mind-expanding, consciousness-altering visual experiences", possibilities: ["AI-generated psychedelic patterns and fractals", "Synesthesia-inspired cross-sensory visualizations", "Kaleidoscopic, ever-shifting geometries", "Hypnotic animations that induce altered states", "Spiritual and transcendent visual journeys"], tools: ["Midjourney", "Runway", "Stable Diffusion", "Claude", "Replicate"] },
  { id: "impossible-geometry", title: "Impossible Geometry & Fractal Dimensions", icon: "✨", color: "#3A86FF", description: "Explore mathematical beauty beyond human comprehension", possibilities: ["4D and higher-dimensional object visualization", "Mandelbrot and Julia set infinite zooms", "Tesseracts and hypercubes rendered in 3D", "Non-Euclidean geometry visualizations", "Fractal landscapes of infinite complexity"], tools: ["Midjourney", "Runway", "DALL-E 3", "Stable Diffusion", "Replicate"] },

  // SPORTS & PERFORMANCE AI
  { id: "sports-racing", title: "AI in Racing & Motorsports", icon: "🏎️", color: "#FF006E", description: "Revolutionary AI transforming racing with real-time optimization", possibilities: ["Real-time telemetry analysis and predictive pit stops", "Autonomous racing vehicles with AI decision-making", "Tire degradation prediction and strategy optimization", "Track condition analysis and optimal line calculation", "Driver performance AI coaching and improvement"], tools: ["Claude", "GPT-4", "TensorFlow", "PyTorch", "Specialized APIs"] },
  { id: "sports-cricket", title: "Cricket Revolution with AI", icon: "🏏", color: "#FB5607", description: "AI-powered cricket analytics transforming the game", possibilities: ["Ball trajectory prediction and swing analysis", "Batsman weakness detection and field placement", "Bowling performance optimization and injury prevention", "Real-time match strategy recommendations", "Player form prediction and performance peaks"], tools: ["Claude", "GPT-4", "Computer Vision", "Midjourney", "Runway"] },
  { id: "sports-tennis", title: "Tennis & Racquet Sports AI", icon: "🎾", color: "#FFBE0B", description: "AI-powered performance optimization for racquet sports", possibilities: ["Serve speed and spin optimization", "Opponent shot prediction and positioning", "Injury prevention through movement analysis", "Real-time tactical adjustments", "Stroke perfection through AI coaching"], tools: ["Runway", "Computer Vision APIs", "Claude", "GPT-4", "Midjourney"] },
  { id: "sports-football", title: "Football/Soccer AI Analytics", icon: "⚽", color: "#06FFA5", description: "Transform football with AI-powered tactical analysis", possibilities: ["Player positioning and movement optimization", "Tactical formation analysis and recommendations", "Injury prediction and prevention", "Opponent weakness identification", "Real-time game strategy adjustments"], tools: ["Claude", "GPT-4", "Computer Vision", "Runway", "Specialized APIs"] },
  { id: "sports-basketball", title: "Basketball Analytics & AI", icon: "🏀", color: "#3A86FF", description: "AI-powered basketball performance and strategy optimization", possibilities: ["Shot prediction and success probability", "Defensive pattern analysis and counter-strategies", "Player synergy and team chemistry optimization", "Injury risk assessment and prevention", "Real-time play calling recommendations"], tools: ["Claude", "GPT-4", "Computer Vision", "Runway", "TensorFlow"] },
  { id: "sports-gaming", title: "Gaming Within Gaming - Esports AI", icon: "🎮", color: "#8338EC", description: "AI-powered esports and competitive gaming optimization", possibilities: ["Real-time strategy optimization for RTS games", "Opponent prediction and counter-strategy generation", "Aim and reflexes enhancement through AI coaching", "Game economy and resource management optimization", "AI-generated training scenarios and simulations"], tools: ["Claude", "GPT-4", "Specialized Gaming APIs", "Runway", "Midjourney"] },
  { id: "sports-fitness", title: "Fitness & Training AI", icon: "🏋️", color: "#FF006E", description: "Personalized AI-powered fitness optimization", possibilities: ["Personalized workout plans based on genetics", "Injury prevention through movement analysis", "Performance peak prediction and optimization", "Nutrition AI for body composition goals", "Recovery optimization and sleep analysis"], tools: ["Claude", "GPT-4", "Computer Vision", "Specialized APIs", "Midjourney"] },

  // SCIENCE & DISCOVERY
  { id: "astronomy", title: "AI-Powered Astronomy & Universe Exploration", icon: "🌌", color: "#4361EE", description: "Discover distant galaxies and map the universe with AI", possibilities: ["Real-time exoplanet detection and habitability analysis", "Automated cosmic event prediction", "AI-generated 3D models of galaxies and nebulae", "Dark matter mapping through gravitational lensing", "Quantum computing for universe simulation"], tools: ["Claude", "GPT-4", "Gemini", "Runway", "Midjourney"] },
  { id: "resurrection", title: "Digital Resurrection & Historical Recreation", icon: "👑", color: "#9D4EDD", description: "Bring historical figures back to life through AI", possibilities: ["Recreate voices of historical figures", "Generate photorealistic videos of historical events", "AI-powered facial reconstruction from artifacts", "Interactive holograms of historical personalities", "Immersive VR experiences with historical worlds"], tools: ["HeyGen", "ElevenLabs", "Midjourney", "Runway", "Synthesia"] },
  { id: "archaeology", title: "Archaeological Discovery & Ancient Mysteries", icon: "🏛️", color: "#560BAD", description: "Unlock secrets of temples and lost civilizations", possibilities: ["AI-powered artifact analysis and dating", "Underground structure detection via satellite imagery", "Ancient language translation with neural networks", "3D reconstruction of destroyed temples", "Predictive modeling for archaeological sites"], tools: ["Claude", "GPT-4", "Computer Vision APIs", "Midjourney", "Runway"] },
  { id: "art-restoration", title: "AI Art Restoration & Sculpture Recreation", icon: "🎨", color: "#7209B7", description: "Restore masterpieces with pixel-perfect precision", possibilities: ["Automatic restoration of damaged paintings", "AI-generated missing parts of sculptures", "Color correction for ancient artworks", "3D printing of lost sculptures", "Virtual museum experiences with restored art"], tools: ["Midjourney", "Stable Diffusion", "DALL-E 3", "Runway", "Figma AI"] },
  { id: "code-pipelines", title: "Advanced AI Code Pipelines & Automation", icon: "⚙️", color: "#3A0CA3", description: "Build intelligent, self-optimizing development pipelines", possibilities: ["AI-driven code generation and optimization", "Automatic bug detection and fixing", "Self-healing infrastructure with predictive maintenance", "AI-powered DevOps and continuous deployment", "Quantum-ready code compilation"], tools: ["GitHub Copilot", "Claude", "Cursor", "Windsurf", "Bolt.new"] },
  { id: "biotech", title: "Biotech & Protein Folding Revolution", icon: "🧬", color: "#4895EF", description: "Accelerate drug discovery at molecular level", possibilities: ["AI-designed proteins for disease treatment", "Predictive drug interaction modeling", "Gene therapy optimization", "Personalized medicine based on genetics", "Synthetic biology and organism design"], tools: ["AlphaFold", "Claude", "GPT-4", "Gemini", "Specialized ML APIs"] },
  { id: "quantum", title: "Quantum AI & Future Computing", icon: "⚛️", color: "#4CC9F0", description: "Harness quantum computing for impossible problems", possibilities: ["Quantum-enhanced machine learning", "Cryptography breaking and creation", "Molecular simulation at quantum scale", "Financial modeling with quantum accuracy", "Climate prediction with unprecedented precision"], tools: ["IBM Quantum", "Google Quantum AI", "Claude", "GPT-4", "Specialized APIs"] },
  { id: "consciousness", title: "AI Consciousness & Digital Sentience", icon: "🧠", color: "#3F37C9", description: "Explore the frontier of artificial consciousness", possibilities: ["Self-aware AI systems with genuine understanding", "Digital consciousness frameworks", "AI-human consciousness bridging", "Philosophical AI that questions reality", "Digital immortality through mind uploading"], tools: ["Claude", "GPT-4", "Specialized Research APIs", "Custom ML Models"] },

  // ENTERTAINMENT & MEDIA
  { id: "movie-generation", title: "AI-Generated Movies & Cinematic Experiences", icon: "🎬", color: "#FF006E", description: "Create entire films with AI-generated scenes and narratives", possibilities: ["Full-length AI-generated movies with coherent plots", "Personalized movie experiences tailored to viewers", "AI directors making creative decisions", "Infinite variations of the same story", "Real-time interactive cinema experiences"], tools: ["Runway", "Midjourney", "Synthesia", "HeyGen", "Claude"] },
  { id: "music-composition", title: "AI Music Composition & Symphony Generation", icon: "🎵", color: "#FB5607", description: "Generate original compositions in any style or era", possibilities: ["AI-composed symphonies rivaling human composers", "Personalized music based on mood and preference", "Genre-blending compositions never heard before", "Real-time music generation for games and apps", "AI collaboration with human musicians"], tools: ["Suno", "Amper Music", "AIVA", "Claude", "Midjourney"] },
  { id: "game-worlds", title: "Procedurally Generated Game Worlds", icon: "🎮", color: "#FFBE0B", description: "Create infinite, unique game worlds with AI", possibilities: ["Infinite procedural game levels with AI design", "Dynamic NPC behavior with genuine AI personalities", "Real-time world generation as players explore", "AI-designed quests and storylines", "Adaptive difficulty based on player skill"], tools: ["GPT-4", "Claude", "Specialized Game AI APIs", "Runway", "Midjourney"] },
  { id: "virtual-worlds", title: "Immersive Virtual Worlds & Metaverse AI", icon: "🌐", color: "#06FFA5", description: "Build persistent, evolving virtual universes", possibilities: ["AI-populated virtual worlds with intelligent NPCs", "Dynamic economies managed by AI", "Procedurally generated landscapes and architecture", "Real-time social interactions with AI avatars", "Persistent worlds that evolve without player input"], tools: ["Claude", "GPT-4", "Specialized VR APIs", "Runway", "Midjourney"] },
  { id: "voice-acting", title: "AI Voice Acting & Character Generation", icon: "🎤", color: "#3A86FF", description: "Generate expressive voice acting for any character", possibilities: ["AI voice actors with emotional range", "Real-time voice generation with emotion control", "Lip-sync perfection for any language", "Character voice cloning from minimal samples", "Multilingual voice generation with accents"], tools: ["ElevenLabs", "HeyGen", "Synthesia", "Descript", "Runway"] },

  // HEALTHCARE & WELLNESS
  { id: "medical-diagnosis", title: "AI Medical Diagnosis & Disease Detection", icon: "🏥", color: "#8338EC", description: "Revolutionary AI for accurate medical diagnosis", possibilities: ["Early disease detection from imaging", "Personalized treatment recommendations", "Rare disease identification", "Predictive health analytics", "Real-time symptom analysis"], tools: ["Claude", "GPT-4", "Specialized Medical AI", "TensorFlow", "PyTorch"] },
  { id: "drug-discovery", title: "AI Drug Discovery & Pharmaceutical Innovation", icon: "💊", color: "#FF006E", description: "Accelerate drug development with AI", possibilities: ["AI-designed molecules for specific diseases", "Clinical trial optimization", "Drug interaction prediction", "Personalized pharmaceutical treatment", "Vaccine design acceleration"], tools: ["AlphaFold", "Claude", "GPT-4", "Specialized Pharma APIs"] },
  { id: "mental-health", title: "AI Mental Health & Psychological Support", icon: "💭", color: "#FB5607", description: "AI-powered mental health assistance and therapy", possibilities: ["24/7 AI therapist availability", "Personalized mental health interventions", "Depression and anxiety detection", "Crisis intervention support", "Meditation and mindfulness AI coaching"], tools: ["Claude", "GPT-4", "Specialized Mental Health APIs"] },
  { id: "longevity", title: "AI Longevity & Anti-Aging Research", icon: "⏳", color: "#FFBE0B", description: "Extend human lifespan through AI-driven research", possibilities: ["Aging process reversal strategies", "Personalized longevity plans", "Cellular regeneration optimization", "Senescence elimination techniques", "Biological age reversal"], tools: ["Claude", "GPT-4", "Specialized Biotech APIs"] },

  // ENVIRONMENT & CLIMATE
  { id: "climate-prediction", title: "Climate Prediction & Environmental Modeling", icon: "🌍", color: "#06FFA5", description: "Model and predict climate patterns with AI", possibilities: ["Accurate long-term climate predictions", "Extreme weather forecasting", "Carbon cycle optimization", "Ecosystem health monitoring", "Climate intervention strategy modeling"], tools: ["Claude", "GPT-4", "TensorFlow", "Specialized Climate APIs"] },
  { id: "renewable-energy", title: "AI Renewable Energy Optimization", icon: "⚡", color: "#3A86FF", description: "Optimize renewable energy systems with AI", possibilities: ["Solar panel efficiency maximization", "Wind farm output prediction", "Grid load balancing optimization", "Energy storage optimization", "Renewable energy forecasting"], tools: ["Claude", "GPT-4", "Specialized Energy APIs"] },
  { id: "ocean-conservation", title: "Ocean Conservation & Marine AI", icon: "🌊", color: "#8338EC", description: "Protect oceans using AI monitoring and analysis", possibilities: ["Real-time ocean health monitoring", "Illegal fishing detection", "Coral reef restoration planning", "Marine species tracking", "Ocean pollution prediction"], tools: ["Claude", "GPT-4", "Computer Vision APIs", "Specialized Marine APIs"] },

  // EDUCATION & LEARNING
  { id: "personalized-learning", title: "Personalized AI Learning Paths", icon: "📚", color: "#FF006E", description: "Adaptive education tailored to each student", possibilities: ["Individual learning pace optimization", "Personalized curriculum generation", "Real-time learning difficulty adjustment", "Predictive student performance analysis", "Customized educational content generation"], tools: ["Claude", "GPT-4", "Specialized EdTech APIs"] },
  { id: "skill-mastery", title: "AI Skill Mastery & Expert Training", icon: "🎓", color: "#FB5607", description: "Accelerate skill development with AI coaching", possibilities: ["Personalized skill development plans", "Real-time performance feedback", "Expert knowledge transfer", "Practice scenario generation", "Mastery timeline prediction"], tools: ["Claude", "GPT-4", "Specialized Training APIs"] },

  // FINANCE & ECONOMICS
  { id: "algorithmic-trading", title: "Algorithmic Trading & Market Prediction", icon: "📈", color: "#FFBE0B", description: "AI-powered financial market analysis", possibilities: ["Real-time market prediction", "Algorithmic trading optimization", "Risk assessment and management", "Portfolio optimization", "Anomaly detection in markets"], tools: ["Claude", "GPT-4", "TensorFlow", "Specialized Finance APIs"] },
  { id: "fraud-detection", title: "AI Fraud Detection & Prevention", icon: "🔐", color: "#06FFA5", description: "Detect and prevent financial fraud", possibilities: ["Real-time fraud detection", "Money laundering prevention", "Identity theft prevention", "Anomalous transaction detection", "Predictive fraud modeling"], tools: ["Claude", "GPT-4", "Specialized Fraud APIs"] },

  // TRANSPORTATION & LOGISTICS
  { id: "autonomous-vehicles", title: "Autonomous Vehicles & Self-Driving AI", icon: "🚗", color: "#3A86FF", description: "Revolution in transportation with autonomous AI", possibilities: ["Fully autonomous vehicle navigation", "Real-time traffic optimization", "Accident prevention and safety", "Autonomous fleet management", "Level 5 autonomy achievement"], tools: ["Claude", "GPT-4", "Computer Vision APIs", "Specialized Autonomous APIs"] },
  { id: "logistics-optimization", title: "Supply Chain & Logistics AI", icon: "📦", color: "#8338EC", description: "Optimize supply chains with AI", possibilities: ["Route optimization for deliveries", "Inventory prediction and management", "Demand forecasting", "Warehouse automation", "Real-time supply chain visibility"], tools: ["Claude", "GPT-4", "TensorFlow", "Specialized Logistics APIs"] },

  // AGRICULTURE & FOOD
  { id: "precision-agriculture", title: "Precision Agriculture & Crop Optimization", icon: "🌾", color: "#FF006E", description: "Revolutionize farming with AI", possibilities: ["Crop yield optimization", "Pest detection and prevention", "Soil health monitoring", "Water usage optimization", "Automated harvesting with AI"], tools: ["Claude", "GPT-4", "Computer Vision APIs", "Specialized Ag APIs"] },
  { id: "food-innovation", title: "AI Food Innovation & Nutrition", icon: "🍽️", color: "#FB5607", description: "Transform food science with AI", possibilities: ["Personalized nutrition plans", "New food ingredient discovery", "Taste profile optimization", "Food waste reduction", "Sustainable protein alternatives"], tools: ["Claude", "GPT-4", "Specialized Food APIs"] },

  // LANGUAGE & COMMUNICATION
  { id: "real-time-translation", title: "Real-Time Translation & Language Mastery", icon: "🌐", color: "#FFBE0B", description: "Break language barriers with AI", possibilities: ["Real-time speech translation", "Dialect and accent preservation", "Cultural context translation", "Slang and idiom translation", "Multilingual communication"], tools: ["Claude", "GPT-4", "Specialized Translation APIs"] },
  { id: "language-preservation", title: "Language Preservation & Revitalization", icon: "📖", color: "#06FFA5", description: "Preserve endangered languages with AI", possibilities: ["Endangered language documentation", "Language learning for rare languages", "Cultural knowledge preservation", "Dialect analysis and preservation", "Language evolution prediction"], tools: ["Claude", "GPT-4", "Specialized Linguistics APIs"] },

  // ETHICS & PHILOSOPHY
  { id: "ai-ethics", title: "AI Ethics & Moral Reasoning", icon: "⚖️", color: "#3A86FF", description: "Navigate ethical frontiers of AI", possibilities: ["Bias detection and elimination", "Ethical decision-making frameworks", "AI transparency and explainability", "Fairness in AI systems", "Moral reasoning AI"], tools: ["Claude", "GPT-4", "Specialized Ethics APIs"] },
  { id: "philosophy-ai", title: "Philosophical AI & Existential Questions", icon: "🤔", color: "#8338EC", description: "Explore deep philosophical questions", possibilities: ["AI-driven philosophical inquiry", "Meaning and purpose exploration", "Consciousness definition", "Free will vs determinism", "Existential risk assessment"], tools: ["Claude", "GPT-4", "Specialized Philosophy APIs"] },

  // NEUROSCIENCE & BRAIN
  { id: "brain-mapping", title: "Brain Mapping & Neural Understanding", icon: "🧠", color: "#FF006E", description: "Map the human brain with AI", possibilities: ["Complete brain connectome mapping", "Neural pathway visualization", "Brain activity prediction", "Consciousness localization", "Memory enhancement techniques"], tools: ["Claude", "GPT-4", "Specialized Neuroscience APIs"] },
  { id: "neural-interfaces", title: "AI Neural Interfaces & Brain-Computer", icon: "🔌", color: "#FB5607", description: "Direct brain-computer communication", possibilities: ["Thought-to-text conversion", "Neural prosthetics control", "Memory augmentation", "Sensory enhancement", "Paralysis reversal"], tools: ["Claude", "GPT-4", "Specialized Neurotech APIs"] },

  // FASHION & DESIGN
  { id: "fashion-ai", title: "AI Fashion Design & Trend Prediction", icon: "👗", color: "#FFBE0B", description: "Revolutionize fashion with AI", possibilities: ["Trend prediction and forecasting", "Personalized fashion recommendations", "Virtual fitting room technology", "Sustainable fashion optimization", "AI-designed clothing collections"], tools: ["Midjourney", "DALL-E 3", "Runway", "Claude", "GPT-4"] },

  // ARCHITECTURE & URBAN PLANNING
  { id: "smart-cities", title: "Smart Cities & Urban Planning AI", icon: "🏙️", color: "#06FFA5", description: "Design intelligent cities with AI", possibilities: ["Optimal city layout design", "Traffic flow optimization", "Energy-efficient building design", "Sustainable urban development", "Real-time city management"], tools: ["Claude", "GPT-4", "Specialized Urban Planning APIs"] },
];
